states = {
'AL' : ['Alabama', 'Ala.', 'Montgomery','AL'],
'AK' : ['Alaska', 'Juneau','AK'],
'AZ' : ['Arizona', 'Ariz.','Phoenix','AZ'],
'AR' : ['Arkansas', 'Little Rock','AR'],
'CA' : ['California', 'San Francisco', 'Calif.','Sacramento','CA'],
'CO' : ['Colorado', 'Colo.', 'Denver','CO'],
'CT' : ['Connecticut', 'Conn.', 'Hartford','CT'],
'DE' : ['Delaware', 'Del.', 'Dover','DE'],
'FL' : ['Florida', 'Fla.', 'Tallahassee','FL'],
'GA' : ['Georgia', 'Ga.','Atlanta','GA'],
'HI' : ['Hawaii','Honolulu','HI'],
'ID' : ['Idaho', 'Boise','ID'],
'IL' : ['Illinois', 'Ill.', 'IL', 'Springfield'],
'IN' : ['Indiana', 'Ind.', 'IN', 'Indianapolis'],
'IA' : ['Iowa', 'IA', 'Des Moines'],
'KS' : ['Kansas', 'Kans.','KS','Topeka'],
'KY' : ['Kentucky','Ky.','KY','Frankfort'],
'LA' : ['Louisiana','La.','LA','Baton Rouge'],
'ME' : ['Maine','ME', 'Augusta'],
'MD' : ['Maryland', 'Md.','MD', 'Annapolis'],
'MA' : ['Massachusetts', 'Mass.','MA','Boston'],
'MI' : ['Michigan','Mich.','MI','Lansing'],
'MN' : ['Minnesota', 'Minn.','MN','St. Paul'],
'MS' : ['Mississippi','Miss.','MS','Jackson'],
'MO' : ['Missouri','Mo.','MO','Jefferson City'],
'MT' : ['Montana','Mont.','MT','Helena'],
'NE' : ['Nebraska','Nebr.','NE', 'Lincoln'],
'NV' : ['Nevada', 'Nev.','NV', 'Carson City'],
'NH' : ['New Hampshire', 'N.H.','NH', 'Concord', 'hampshire'],
'NJ' : ['New Jersey', 'N.J.','NJ', 'Trenton','jersey'],
'NM' : ['New Mexico', 'N.M.','NM', 'Santa Fe','mexico'],
'NY' : ['New York', 'N.Y.','NY', 'Albany','york'],
'NC' : ['North Carolina', 'N.C.','NC', 'Raleigh'],
'ND' : ['North Dakota','N.D.','ND','Bismarck','dakota'],
'OH' : ['Ohio', 'OH', 'Columbus'],
'OK' : ['Oklahoma', 'Okla.','OK','Oklahoma City'],
'OR' : ['Oregon', 'Ore.','OR', 'Salem'],
'PA' : ['Pennsylvania','Pa.','PA','Harrisburg'],
'RI' : ['Rhode Island', 'R.I.', 'RI', 'Providence'],
'SC' : ['South Carolina','S.C.','SC','Columbia','carolina'],
'SD' : ['South Dakota', 'S.D.','SD', 'Pierre'],
'TN' : ['Tennessee', 'Tenn.','TN', 'Nashville'],
'TX' : ['Texas', 'Tex.','TX', 'Austin'],
'UT' : ['Utah', 'UT', 'Salt Lake City','salt'],
'VT' : ['Vermont', 'Vt.', 'VT', 'Montpelier'],
'VA' : ['Virginia', 'Va.','VA', 'Richmond'],
'WA' : ['Washington', 'Wash.','WA', 'Olympia','Seattle'],
'WV' : ['West Virginia', 'W.Va.','WV', 'Charleston'],
'WI' : ['Wisconsin', 'Wis.', 'WI', 'Madison'],
'WY' : ['Wyoming', 'Wyo.', 'WY', 'Cheyenne'],
'DC' : ['D.C.','DC','Washington,DC']
}
